[General]
ScreenWidth="1920"
ScreenHeight="1080"
Font="Open Sans"
FontSize="12"
KeyboardSize="0.4"
RoundCorners="20"
HourFormat="HH:mm:ss"
DateFormat="dddd d"

BackgroundPlaceholder="Backgrounds/wallpaper.jpg"
Background="Backgrounds/wallpaper.jpg"
DimBackground="0.0"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

HeaderTextColor="#d8d8ff"
DateTextColor="#d8d8ff"
TimeTextColor="#d8d8ff"
FormBackgroundColor="#242455"
BackgroundColor="#242455"
DimBackgroundColor="#242455"
LoginFieldBackgroundColor="#d8d8ff"
PasswordFieldBackgroundColor="#d8d8ff"
LoginFieldTextColor="#d8d8ff"
PasswordFieldTextColor="#d8d8ff"
UserIconColor="#d8d8ff"
PasswordIconColor="#d8d8ff"
PlaceholderTextColor="#6c6caa"
WarningColor="#d8d8ff"
LoginButtonTextColor="#6c6caa"
LoginButtonBackgroundColor="#d8d8ff"
SystemButtonsIconsColor="#d8d8ff"
SessionButtonTextColor="#d8d8ff"
VirtualKeyboardButtonTextColor="#d8d8ff"
DropdownTextColor="#6c6caa"
DropdownSelectedBackgroundColor="#f8f8ff"
DropdownBackgroundColor="#d8d8ff"
HighlightTextColor="#484855"
HighlightBackgroundColor="#d8d8ff"
HighlightBorderColor="transparent"
HoverUserIconColor="#6c6caa"
HoverPasswordIconColor="#6c6caa"
HoverSystemButtonsIconsColor="#6c6caa"
HoverSessionButtonTextColor="#6c6caa"
HoverVirtualKeyboardButtonTextColor="#6c6caa"

PartialBlur="true"
BlurMax="8"
Blur="2.0"
HaveFormBackground="true"
FormPosition="right"
VirtualKeyboardPosition="right"

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"
ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
