#!/usr/bin/env bash
set -euo pipefail

THEME="${1:-md3-cobalt-night}"

case "$THEME" in
  md3-cobalt-night)
    BG="#0F1117"
    TEXT="#E0E2F0"
    ACCENT="#9BBDE8"
    WARNING="#F2D479"
    CRITICAL="#F2A8B8"
    CHARGING="#86D5A0"
    BORDER_ACTIVE="9BBDE8cc"
    BORDER_INACTIVE="2E3148aa"
    SURFACE_CONTAINER="#252740"
    SURFACE_CONTAINER_HIGH="#2E3148"
    SURFACE_BRIGHT="#3A3E60"
    TEXT_SECONDARY="#8E90A8"
    ;;
  md3-sage-forest)
    BG="#0D1410"
    TEXT="#DCF0E2"
    ACCENT="#7EC996"
    WARNING="#EDD678"
    CRITICAL="#F2A8A8"
    CHARGING="#72CAD0"
    BORDER_ACTIVE="7EC996cc"
    BORDER_INACTIVE="2A3D2Daa"
    SURFACE_CONTAINER="#203028"
    SURFACE_CONTAINER_HIGH="#2A3D2D"
    SURFACE_BRIGHT="#385045"
    TEXT_SECONDARY="#8AAE92"
  ;;
  md3-rose-quartz)
    BG="#170E12"
    TEXT="#F0DEE5"
    ACCENT="#EEA8C0"
    WARNING="#F0D47A"
    CRITICAL="#F5A0A8"
    CHARGING="#A0C8F0"
    BORDER_ACTIVE="EEA8C0cc"
    BORDER_INACTIVE="4A2838aa"
    SURFACE_CONTAINER="#381C2C"
    SURFACE_CONTAINER_HIGH="#4A2838"
    SURFACE_BRIGHT="#603050"
    TEXT_SECONDARY="#A88090"
  ;;
  md3-amethyst)
    BG="#110E18"
    TEXT="#E8E0F5"
    ACCENT="#C8B0F0"
    WARNING="#F0D478"
    CRITICAL="#F5A0A8"
    CHARGING="#86D0C0"
    BORDER_ACTIVE="C8B0F0cc"
    BORDER_INACTIVE="3A3050aa"
    SURFACE_CONTAINER="#2C2440"
    SURFACE_CONTAINER_HIGH="#3A3050"
    SURFACE_BRIGHT="#504068"
    TEXT_SECONDARY="#9A90B8"
  ;;
  md3-amber-dusk)
    BG="#18120A"
    TEXT="#F0E8D5"
    ACCENT="#F0B87A"
    WARNING="#F0D050"
    CRITICAL="#F0907A"
    CHARGING="#90C890"
    BORDER_ACTIVE="F0B87Acc"
    BORDER_INACTIVE="483220aa"
    SURFACE_CONTAINER="#382818"
    SURFACE_CONTAINER_HIGH="#483220"
    SURFACE_BRIGHT="#604030"
    TEXT_SECONDARY="#A88860"
  ;;
  md3-arctic-mist)
    BG="#080F14"
    TEXT="#D8EEF5"
    ACCENT="#7ECCE8"
    WARNING="#F0D478"
    CRITICAL="#F2A8A8"
    CHARGING="#90D4A8"
    BORDER_ACTIVE="7ECCE8cc"
    BORDER_INACTIVE="1E3848aa"
    SURFACE_CONTAINER="#162838"
    SURFACE_CONTAINER_HIGH="#1E3848"
    SURFACE_BRIGHT="#2A4A60"
    TEXT_SECONDARY="#7A9AA8"
    ;;
  *)
    echo "Unknown theme: $THEME"
    exit 1
    ;;
esac

# Helper: convert #RRGGBB to "R, G, B"
hex_to_rgb() {
    local hex="${1#\#}"
    printf "%d, %d, %d" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

# A) Write Waybar colors.css
cat > "$HOME/.config/waybar/colors.css" << CSSEOF
/* Auto-generated by apply-theme.sh — do not edit */
@define-color bg ${BG};
@define-color text ${TEXT};
@define-color accent ${ACCENT};
@define-color warning ${WARNING};
@define-color critical ${CRITICAL};
@define-color charging ${CHARGING};
CSSEOF
pkill -SIGUSR2 waybar || true

# B) Apply Hyprland border colors
hyprctl keyword general:col.active_border "rgba(${BORDER_ACTIVE})" 2>/dev/null || true
hyprctl keyword general:col.inactive_border "rgba(${BORDER_INACTIVE})" 2>/dev/null || true

# D) Write Rofi launcher colors
cat > "$HOME/.config/rofi/themes/colors.rasi" << ROFIEOF
* {
    bg-panel:         rgba($(hex_to_rgb "$BG"), 80%);
    bg-container:     rgba($(hex_to_rgb "$SURFACE_CONTAINER"), 80%);
    bg-container-hi:  ${SURFACE_CONTAINER_HIGH};
    bg-bright:        ${SURFACE_BRIGHT};
    accent:           ${ACCENT};
    accent-dim:       rgba($(hex_to_rgb "$ACCENT"), 18%);
    text-primary:     ${TEXT};
    text-secondary:   ${TEXT_SECONDARY};
    separator-line:   rgba($(hex_to_rgb "$TEXT"), 10%);
}
ROFIEOF
