#!/usr/bin/env bash
# Apply a quickshell theme (md3-*) to the rest of the desktop:
#   * Hyprland border colors — live (hyprctl) and persisted in
#     ~/.config/hypr/theme.lua, which hyprland.lua loads when present
#   * GTK3 / GTK4 user-level gtk.css (the dotfiles theme has no GTK theme
#     package; Adwaita + these named-color overrides carry the palette)
#   * Qt colors: generated qt5ct/qt6ct color schemes + custom palette
#     (with the Kvantum style the latter covers non-Kvantum widgets)
#   * Kvantum: a recolored copy of the shipped catppuccin theme, selected in
#     ~/.config/Kvantum/kvantum.kvconfig
#   * Ghostty palette (~/.config/ghostty/theme.conf, included optionally by
#     the main config)
#   * Rofi launcher colors (~/.config/rofi/colors.rasi, the file launcher.rasi imports)
# Waybar/dunst are intentionally not used in HyprTomic (quickshell owns the
# bar/notifications), so no waybar colors.css is written.
#
# Run on every shell start (ControlCenter) and on theme changes, so the whole
# desktop follows ~/.config/quickshell/ii/current-theme.
set -euo pipefail

THEME="${1:-md3-cobalt-night}"

case "$THEME" in
  md3-cobalt-night)
    BG="#0F1117"; TEXT="#E0E2F0"; ACCENT="#9BBDE8"
    WARNING="#F2D479"; CRITICAL="#F2A8B8"; CHARGING="#86D5A0"
    BORDER_ACTIVE="9BBDE8cc"; BORDER_INACTIVE="2E3148aa"
    SURFACE="#1A1C28"; SURFACE_LOW="#1A1C28"; SURFACE_CONTAINER="#252740"
    SURFACE_CONTAINER_HIGH="#2E3148"; SURFACE_BRIGHT="#3A3E60"
    TEXT_SECONDARY="#8E90A8"; TOGGLE_OFF="#404460"
    PRIMARY_CONTAINER="#1E3058"; ON_PRIMARY_CONTAINER="#C8D8F5"
    ERROR_CONTAINER="#4A2030"; ON_ERROR_CONTAINER="#F5D8DE"
    MAGENTA="#B8A8E8"; CYAN="#8ED8E8"
    ;;
  md3-sage-forest)
    BG="#0D1410"; TEXT="#DCF0E2"; ACCENT="#7EC996"
    WARNING="#EDD678"; CRITICAL="#F2A8A8"; CHARGING="#72CAD0"
    BORDER_ACTIVE="7EC996cc"; BORDER_INACTIVE="2A3D2Daa"
    SURFACE="#172219"; SURFACE_LOW="#172219"; SURFACE_CONTAINER="#203028"
    SURFACE_CONTAINER_HIGH="#2A3D2D"; SURFACE_BRIGHT="#385045"
    TEXT_SECONDARY="#8AAE92"; TOGGLE_OFF="#3A5040"
    PRIMARY_CONTAINER="#1A4028"; ON_PRIMARY_CONTAINER="#B8E8C8"
    ERROR_CONTAINER="#4A2828"; ON_ERROR_CONTAINER="#F5D8D8"
    MAGENTA="#C0A8D8"; CYAN="#7EC8C0"
    ;;
  md3-rose-quartz)
    BG="#170E12"; TEXT="#F0DEE5"; ACCENT="#EEA8C0"
    WARNING="#F0D47A"; CRITICAL="#F5A0A8"; CHARGING="#A0C8F0"
    BORDER_ACTIVE="EEA8C0cc"; BORDER_INACTIVE="4A2838aa"
    SURFACE="#281520"; SURFACE_LOW="#281520"; SURFACE_CONTAINER="#381C2C"
    SURFACE_CONTAINER_HIGH="#4A2838"; SURFACE_BRIGHT="#603050"
    TEXT_SECONDARY="#A88090"; TOGGLE_OFF="#603048"
    PRIMARY_CONTAINER="#4A1C30"; ON_PRIMARY_CONTAINER="#F5D0E0"
    ERROR_CONTAINER="#602830"; ON_ERROR_CONTAINER="#F5D8DE"
    MAGENTA="#E8A8D8"; CYAN="#90D0E0"
    ;;
  md3-amethyst)
    BG="#110E18"; TEXT="#E8E0F5"; ACCENT="#C8B0F0"
    WARNING="#F0D478"; CRITICAL="#F5A0A8"; CHARGING="#86D0C0"
    BORDER_ACTIVE="C8B0F0cc"; BORDER_INACTIVE="3A3050aa"
    SURFACE="#1E1A2C"; SURFACE_LOW="#1E1A2C"; SURFACE_CONTAINER="#2C2440"
    SURFACE_CONTAINER_HIGH="#3A3050"; SURFACE_BRIGHT="#504068"
    TEXT_SECONDARY="#9A90B8"; TOGGLE_OFF="#504068"
    PRIMARY_CONTAINER="#3A2870"; ON_PRIMARY_CONTAINER="#E8D8FF"
    ERROR_CONTAINER="#5A2838"; ON_ERROR_CONTAINER="#F5D8E0"
    MAGENTA="#D8A8F0"; CYAN="#88C8E0"
    ;;
  md3-amber-dusk)
    BG="#18120A"; TEXT="#F0E8D5"; ACCENT="#F0B87A"
    WARNING="#F0D050"; CRITICAL="#F0907A"; CHARGING="#90C890"
    BORDER_ACTIVE="F0B87Acc"; BORDER_INACTIVE="483220aa"
    SURFACE="#281E10"; SURFACE_LOW="#281E10"; SURFACE_CONTAINER="#382818"
    SURFACE_CONTAINER_HIGH="#483220"; SURFACE_BRIGHT="#604030"
    TEXT_SECONDARY="#A88860"; TOGGLE_OFF="#604030"
    PRIMARY_CONTAINER="#503018"; ON_PRIMARY_CONTAINER="#F8DEB8"
    ERROR_CONTAINER="#603028"; ON_ERROR_CONTAINER="#F8D8D0"
    MAGENTA="#E0A8C0"; CYAN="#90C8C8"
    ;;
  md3-arctic-mist)
    BG="#080F14"; TEXT="#D8EEF5"; ACCENT="#7ECCE8"
    WARNING="#F0D478"; CRITICAL="#F2A8A8"; CHARGING="#90D4A8"
    BORDER_ACTIVE="7ECCE8cc"; BORDER_INACTIVE="1E3848aa"
    SURFACE="#101C26"; SURFACE_LOW="#101C26"; SURFACE_CONTAINER="#162838"
    SURFACE_CONTAINER_HIGH="#1E3848"; SURFACE_BRIGHT="#2A4A60"
    TEXT_SECONDARY="#7A9AA8"; TOGGLE_OFF="#2A4A60"
    PRIMARY_CONTAINER="#103858"; ON_PRIMARY_CONTAINER="#C0E4F5"
    ERROR_CONTAINER="#4A2830"; ON_ERROR_CONTAINER="#F5D8DE"
    MAGENTA="#B8A8E8"; CYAN="#90E0D8"
    ;;
  *)
    echo "Unknown theme: $THEME" >&2
    exit 1
    ;;
esac

mkdir -p "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0" "$HOME/.config/rofi"

# Helper: convert #RRGGBB to "R, G, B"
hex_to_rgb() {
    local hex="${1#\#}"
    printf "%d, %d, %d" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

# ── A) GTK4 named-color overrides ─────────────────────────────────────────
cat > "$HOME/.config/gtk-4.0/gtk.css" << CSSEOF
/* Generated by apply-theme.sh ($THEME) -- do not edit */
@define-color accent_color ${ACCENT};
@define-color accent_bg_color ${ACCENT};
@define-color accent_fg_color ${BG};
@define-color destructive_bg_color ${ERROR_CONTAINER};
@define-color destructive_fg_color ${ON_ERROR_CONTAINER};
@define-color destructive_color ${CRITICAL};
@define-color success_bg_color #374B3E;
@define-color success_fg_color #D1E9D6;
@define-color success_color #B5CCBA;
@define-color warning_bg_color #4A3A20;
@define-color warning_fg_color #F0E8D0;
@define-color warning_color ${WARNING};

@define-color window_bg_color ${BG};
@define-color window_fg_color ${TEXT};
@define-color headerbar_bg_color ${SURFACE_CONTAINER};
@define-color headerbar_fg_color ${TEXT};
@define-color headerbar_backdrop_color ${SURFACE_LOW};
@define-color headerbar_backdrop_fg_color ${TEXT_SECONDARY};
@define-color card_bg_color ${SURFACE_LOW};
@define-color card_fg_color ${TEXT};
@define-color popover_bg_color ${SURFACE_CONTAINER_HIGH};
@define-color popover_fg_color ${TEXT};
@define-color dialog_bg_color ${SURFACE_CONTAINER};
@define-color dialog_fg_color ${TEXT};
@define-color view_bg_color ${BG};
@define-color view_fg_color ${TEXT};
@define-color sidebar_bg_color ${SURFACE_CONTAINER};
@define-color sidebar_fg_color ${TEXT};
@define-color sidebar_backdrop_color ${SURFACE_LOW};
@define-color sidebar_backdrop_fg_color ${TEXT_SECONDARY};
@define-color secondary_sidebar_bg_color ${SURFACE_LOW};
@define-color secondary_sidebar_fg_color ${TEXT};
@define-color sidebar_row_active_bg_color ${PRIMARY_CONTAINER};
@define-color sidebar_row_active_fg_color ${ON_PRIMARY_CONTAINER};
@define-color thumbnail_bg_color ${SURFACE_BRIGHT};
@define-color thumbnail_fg_color ${TEXT};
@define-color outline ${TOGGLE_OFF};
@define-color outline_strong ${SURFACE_CONTAINER_HIGH};

@define-color surface_container_lowest ${BG};
@define-color surface_container_low ${SURFACE_LOW};
@define-color surface_container ${SURFACE_CONTAINER};
@define-color surface_container_high ${SURFACE_CONTAINER_HIGH};
@define-color surface_container_highest ${SURFACE_BRIGHT};
@define-color on_surface ${TEXT};
@define-color on_surface_variant ${TEXT_SECONDARY};
@define-color surface_variant ${SURFACE_CONTAINER};
@define-color inverse_surface ${TEXT};
@define-color inverse_on_surface ${BG};
@define-color inverse_primary ${ACCENT};

* {
  caret-color: @accent_color;
}

window {
  background: @window_bg_color;
}

.text-button,
button,
popover.background > contents,
.navigation-sidebar row,
switch slider {
  border-radius: 999px;
}
CSSEOF

# ── B) GTK3 palette ───────────────────────────────────────────────────────
cat > "$HOME/.config/gtk-3.0/gtk.css" << CSSEOF
/* Generated by apply-theme.sh ($THEME) -- do not edit */
@define-color bg_color ${BG};
@define-color fg_color ${TEXT};
@define-color base_color ${BG};
@define-color text_color ${TEXT};
@define-color selected_bg_color ${ACCENT};
@define-color selected_fg_color ${BG};
@define-color tooltip_bg_color ${SURFACE_CONTAINER_HIGH};
@define-color tooltip_fg_color ${TEXT};
@define-color theme_bg_color ${BG};
@define-color theme_fg_color ${TEXT};
@define-color theme_base_color ${BG};
@define-color theme_text_color ${TEXT};
@define-color theme_selected_bg_color ${ACCENT};
@define-color theme_selected_fg_color ${BG};
@define-color theme_unfocused_bg_color ${SURFACE_LOW};
@define-color theme_unfocused_fg_color ${TEXT_SECONDARY};
@define-color theme_unfocused_base_color ${BG};
@define-color theme_unfocused_text_color ${TEXT_SECONDARY};
@define-color borders ${SURFACE_CONTAINER};
@define-color unfocused_borders ${SURFACE_LOW};
@define-color warning_color ${WARNING};
@define-color error_color ${CRITICAL};
@define-color success_color ${CHARGING};
@define-color insensitive_bg_color ${SURFACE_LOW};
@define-color insensitive_fg_color ${TEXT_SECONDARY};
CSSEOF

# ── C) Hyprland border colors ────────────────────────────────────────────
hyprctl keyword general:col.active_border "rgba(${BORDER_ACTIVE})" 2>/dev/null || true
hyprctl keyword general:col.inactive_border "rgba(${BORDER_INACTIVE})" 2>/dev/null || true

# ── D) Rofi launcher colors (colors.rasi is what launcher.rasi imports) ──
cat > "$HOME/.config/rofi/colors.rasi" << ROFIEOF
* {
    bg-panel:         rgba($(hex_to_rgb "$BG"), 80%);
    bg-container:     rgba($(hex_to_rgb "$SURFACE_CONTAINER"), 80%);
    bg-container-hi:  ${SURFACE_CONTAINER_HIGH};
    bg-bright:        ${SURFACE_BRIGHT};
    accent:           ${ACCENT};
    accent-dim:       rgba($(hex_to_rgb "$ACCENT"), 18%);
    text-primary:     ${TEXT};
    text-secondary:   ${TEXT_SECONDARY};
    separator-line:   rgba($(hex_to_rgb "$TEXT"), 10%);
}
ROFIEOF

# ── E) Hyprland persisted colors ──────────────────────────────────────────
# hyprland.lua loads this file (when present) and applies the borders on
# startup, so the saved theme survives logout/login. The live update is the
# hyprctl call in section C.
mkdir -p "$HOME/.config/hypr"
cat > "$HOME/.config/hypr/theme.lua" << LUAEOF
-- Generated by apply-theme.sh ($THEME) -- do not edit
return {
    active_border         = "rgba(${BORDER_ACTIVE})",
    inactive_border       = "rgba(${BORDER_INACTIVE})",
    group_active_border   = "rgba(${BORDER_ACTIVE})",
    group_inactive_border = "rgba(${BORDER_INACTIVE})",
}
LUAEOF

# ── F) Qt colors (qt5ct / qt6ct) ──────────────────────────────────────────
# QtCt color schemes are QPalette dumps: a [ColorScheme] section with three
# comma-separated #AARRGGBB lists in QPalette::ColorRole order.
qt_hex() { printf '#ff%s' "${1#\#}"; }
qt_hex_a() { printf '#80%s' "${1#\#}"; }

QT_ACTIVE="$(qt_hex "$TEXT"), $(qt_hex "$SURFACE_CONTAINER"), $(qt_hex "$SURFACE_BRIGHT"), \
$(qt_hex "$SURFACE_CONTAINER_HIGH"), $(qt_hex "$SURFACE_LOW"), $(qt_hex "$SURFACE_CONTAINER"), \
$(qt_hex "$TEXT"), $(qt_hex "$CRITICAL"), $(qt_hex "$TEXT"), $(qt_hex "$SURFACE_LOW"), \
$(qt_hex "$BG"), $(qt_hex "$BG"), $(qt_hex "$ACCENT"), $(qt_hex "$BG"), $(qt_hex "$ACCENT"), \
$(qt_hex "$ACCENT"), $(qt_hex "$SURFACE_CONTAINER"), #ffffffff, $(qt_hex "$SURFACE_CONTAINER_HIGH"), \
$(qt_hex "$TEXT"), $(qt_hex_a "$TEXT_SECONDARY")"

QT_DISABLED="$(qt_hex "$TEXT_SECONDARY"), $(qt_hex "$SURFACE_CONTAINER"), $(qt_hex "$SURFACE_BRIGHT"), \
$(qt_hex "$SURFACE_CONTAINER_HIGH"), $(qt_hex "$SURFACE_LOW"), $(qt_hex "$SURFACE_CONTAINER"), \
$(qt_hex "$TEXT_SECONDARY"), $(qt_hex "$CRITICAL"), $(qt_hex "$TEXT_SECONDARY"), $(qt_hex "$SURFACE_LOW"), \
$(qt_hex "$BG"), $(qt_hex "$BG"), $(qt_hex "$ACCENT"), $(qt_hex "$BG"), $(qt_hex "$ACCENT"), \
$(qt_hex "$ACCENT"), $(qt_hex "$SURFACE_CONTAINER"), #ffffffff, $(qt_hex "$SURFACE_CONTAINER_HIGH"), \
$(qt_hex "$TEXT"), $(qt_hex_a "$TEXT_SECONDARY")"

QT_INACTIVE="$QT_ACTIVE"

write_qt_scheme() { # $1 = config dir (without the colors subdir)
    mkdir -p "$1/colors"
    cat > "$1/colors/${THEME}.conf" << QTEOF
[ColorScheme]
active_colors=${QT_ACTIVE}
disabled_colors=${QT_DISABLED}
inactive_colors=${QT_INACTIVE}
QTEOF
}

set_qt_conf() { # $1 = conf file, $2 = config dir name (for the scheme path)
    local conf="$1"
    mkdir -p "$(dirname "$conf")"
    touch "$conf"
    grep -q '^\[Appearance\]' "$conf" || printf '\n[Appearance]\n' >> "$conf"
    for kv in "color_scheme_path=$HOME/.config/$2/colors/${THEME}.conf" "custom_palette=true"; do
        local key="${kv%%=*}"
        if grep -q "^${key}=" "$conf"; then
            sed -i "s|^${key}=.*|${kv}|" "$conf"
        else
            sed -i "/^\[Appearance\]/a ${kv}" "$conf"
        fi
    done
}

write_qt_scheme "$HOME/.config/qt6ct"
set_qt_conf "$HOME/.config/qt6ct/qt6ct.conf" qt6ct
write_qt_scheme "$HOME/.config/qt5ct"
set_qt_conf "$HOME/.config/qt5ct/qt5ct.conf" qt5ct

# ── G) Kvantum (recolored copy of the shipped catppuccin theme) ───────────
# The catppuccin theme lives in skel; recoloring it keeps the Kvantum widgets
# (the Qt style is kvantum-dark) aligned with the shell theme. Running apps
# pick the new colors up on restart.
KV_SRC="$HOME/.config/Kvantum/catppuccin-mocha-blue"
KV_DST="$HOME/.config/Kvantum/hyprtomic"
if [ -f "$KV_SRC/catppuccin-mocha-blue.kvconfig" ]; then
    mkdir -p "$KV_DST"
    cp "$KV_SRC/catppuccin-mocha-blue.kvconfig" "$KV_DST/hyprtomic.kvconfig"
    cp "$KV_SRC/catppuccin-mocha-blue.svg" "$KV_DST/hyprtomic.svg"

    kv_map() { # $1 = catppuccin hex (no #), $2 = theme hex (no #)
        sed -i "s/#$1/#$2/g" "$KV_DST/hyprtomic.kvconfig" "$KV_DST/hyprtomic.svg"
    }
    kv_map 1E1E2E "${BG#\#}"                      # base       -> window
    kv_map 181825 "${SURFACE_LOW#\#}"             # mantle     -> base/view
    kv_map 11111B "${BG#\#}"                      # crust      -> darkest
    kv_map 313244 "${SURFACE_CONTAINER#\#}"       # surface0   -> buttons
    kv_map 45475A "${SURFACE_CONTAINER_HIGH#\#}"  # surface1   -> borders
    kv_map 585B70 "${TOGGLE_OFF#\#}"              # surface2   -> disabled/outline
    kv_map 6C7086 "${TEXT_SECONDARY#\#}"          # overlay0
    kv_map 7F849C "${TEXT_SECONDARY#\#}"          # overlay1
    kv_map 9399B2 "${TEXT_SECONDARY#\#}"          # overlay2
    kv_map BAC2DE "${TEXT_SECONDARY#\#}"          # subtext1
    kv_map A6ADC8 "${TEXT_SECONDARY#\#}"          # subtext0
    kv_map CDD6F4 "${TEXT#\#}"                    # text
    kv_map 89B4FA "${ACCENT#\#}"                  # blue (also #89B4FA4D highlight)
    kv_map 7EA5E6 "${ACCENT#\#}"                  # hover blue
    kv_map 97BBF9 "${ACCENT#\#}"                  # visited link
    kv_map F38BA8 "${CRITICAL#\#}"                # red
    kv_map CBA6F7 "${MAGENTA#\#}"                 # mauve
    kv_map F9E2AF "${WARNING#\#}"                 # yellow
    kv_map A6E3A1 "${CHARGING#\#}"                # green
    kv_map 94E2D5 "${CYAN#\#}"                    # teal
    kv_map F5C2E7 "${MAGENTA#\#}"                 # pink
    kv_map FAB387 "${WARNING#\#}"                 # peach
    kv_map F2CDCD "${TEXT#\#}"                    # flamingo
    kv_map F5E0DC "${TEXT#\#}"                    # rosewater
    sed -i "s/^comment=.*/comment=HyprTomic (${THEME})/" "$KV_DST/hyprtomic.kvconfig"

    printf '[General]\ntheme=hyprtomic\n' > "$HOME/.config/Kvantum/kvantum.kvconfig"
fi

# ── H) Ghostty palette (optional include in ~/.config/ghostty/config) ─────
GHOSTTY_DIR="$HOME/.config/ghostty"
if [ -d "$GHOSTTY_DIR" ]; then
    cat > "$GHOSTTY_DIR/theme.conf" << GHOSTTYEOF
# Generated by apply-theme.sh ($THEME) -- do not edit
background = ${BG}
foreground = ${TEXT}
cursor-color = ${ACCENT}
cursor-text = ${BG}
selection-background = ${SURFACE_CONTAINER_HIGH}
selection-foreground = ${TEXT}
palette = 0=${SURFACE_LOW}
palette = 1=${CRITICAL}
palette = 2=${CHARGING}
palette = 3=${WARNING}
palette = 4=${ACCENT}
palette = 5=${MAGENTA}
palette = 6=${CYAN}
palette = 7=${TEXT}
palette = 8=${TEXT_SECONDARY}
palette = 9=${CRITICAL}
palette = 10=${CHARGING}
palette = 11=${WARNING}
palette = 12=${ACCENT}
palette = 13=${MAGENTA}
palette = 14=${CYAN}
palette = 15=${TEXT}
GHOSTTYEOF
fi