#!/usr/bin/env bash
# Apply a quickshell theme (md3-*) to the rest of the desktop:
#   * Hyprland border colors (hyprctl)
#   * GTK3 / GTK4 user-level gtk.css (the dotfiles theme has no GTK theme
#     package; Adwaita + these named-color overrides carry the palette)
#   * Rofi launcher colors (~/.config/rofi/colors.rasi, the file launcher.rasi imports)
# Waybar/dunst are intentionally not used in HyprTomic (quickshell owns the
# bar/notifications), so no waybar colors.css is written.
set -euo pipefail

THEME="${1:-md3-cobalt-night}"

case "$THEME" in
  md3-cobalt-night)
    BG="#0F1117"; TEXT="#E0E2F0"; ACCENT="#9BBDE8"
    WARNING="#F2D479"; CRITICAL="#F2A8B8"; CHARGING="#86D5A0"
    BORDER_ACTIVE="9BBDE8cc"; BORDER_INACTIVE="2E3148aa"
    SURFACE="#1A1C28"; SURFACE_LOW="#1A1C28"; SURFACE_CONTAINER="#252740"
    SURFACE_CONTAINER_HIGH="#2E3148"; SURFACE_BRIGHT="#3A3E60"
    TEXT_SECONDARY="#8E90A8"; TOGGLE_OFF="#404460"
    PRIMARY_CONTAINER="#1E3058"; ON_PRIMARY_CONTAINER="#C8D8F5"
    ERROR_CONTAINER="#4A2030"; ON_ERROR_CONTAINER="#F5D8DE"
    ;;
  md3-sage-forest)
    BG="#0D1410"; TEXT="#DCF0E2"; ACCENT="#7EC996"
    WARNING="#EDD678"; CRITICAL="#F2A8A8"; CHARGING="#72CAD0"
    BORDER_ACTIVE="7EC996cc"; BORDER_INACTIVE="2A3D2Daa"
    SURFACE="#172219"; SURFACE_LOW="#172219"; SURFACE_CONTAINER="#203028"
    SURFACE_CONTAINER_HIGH="#2A3D2D"; SURFACE_BRIGHT="#385045"
    TEXT_SECONDARY="#8AAE92"; TOGGLE_OFF="#3A5040"
    PRIMARY_CONTAINER="#1A4028"; ON_PRIMARY_CONTAINER="#B8E8C8"
    ERROR_CONTAINER="#4A2828"; ON_ERROR_CONTAINER="#F5D8D8"
    ;;
  md3-rose-quartz)
    BG="#170E12"; TEXT="#F0DEE5"; ACCENT="#EEA8C0"
    WARNING="#F0D47A"; CRITICAL="#F5A0A8"; CHARGING="#A0C8F0"
    BORDER_ACTIVE="EEA8C0cc"; BORDER_INACTIVE="4A2838aa"
    SURFACE="#281520"; SURFACE_LOW="#281520"; SURFACE_CONTAINER="#381C2C"
    SURFACE_CONTAINER_HIGH="#4A2838"; SURFACE_BRIGHT="#603050"
    TEXT_SECONDARY="#A88090"; TOGGLE_OFF="#603048"
    PRIMARY_CONTAINER="#4A1C30"; ON_PRIMARY_CONTAINER="#F5D0E0"
    ERROR_CONTAINER="#602830"; ON_ERROR_CONTAINER="#F5D8DE"
    ;;
  md3-amethyst)
    BG="#110E18"; TEXT="#E8E0F5"; ACCENT="#C8B0F0"
    WARNING="#F0D478"; CRITICAL="#F5A0A8"; CHARGING="#86D0C0"
    BORDER_ACTIVE="C8B0F0cc"; BORDER_INACTIVE="3A3050aa"
    SURFACE="#1E1A2C"; SURFACE_LOW="#1E1A2C"; SURFACE_CONTAINER="#2C2440"
    SURFACE_CONTAINER_HIGH="#3A3050"; SURFACE_BRIGHT="#504068"
    TEXT_SECONDARY="#9A90B8"; TOGGLE_OFF="#504068"
    PRIMARY_CONTAINER="#3A2870"; ON_PRIMARY_CONTAINER="#E8D8FF"
    ERROR_CONTAINER="#5A2838"; ON_ERROR_CONTAINER="#F5D8E0"
    ;;
  md3-amber-dusk)
    BG="#18120A"; TEXT="#F0E8D5"; ACCENT="#F0B87A"
    WARNING="#F0D050"; CRITICAL="#F0907A"; CHARGING="#90C890"
    BORDER_ACTIVE="F0B87Acc"; BORDER_INACTIVE="483220aa"
    SURFACE="#281E10"; SURFACE_LOW="#281E10"; SURFACE_CONTAINER="#382818"
    SURFACE_CONTAINER_HIGH="#483220"; SURFACE_BRIGHT="#604030"
    TEXT_SECONDARY="#A88860"; TOGGLE_OFF="#604030"
    PRIMARY_CONTAINER="#503018"; ON_PRIMARY_CONTAINER="#F8DEB8"
    ERROR_CONTAINER="#603028"; ON_ERROR_CONTAINER="#F8D8D0"
    ;;
  md3-arctic-mist)
    BG="#080F14"; TEXT="#D8EEF5"; ACCENT="#7ECCE8"
    WARNING="#F0D478"; CRITICAL="#F2A8A8"; CHARGING="#90D4A8"
    BORDER_ACTIVE="7ECCE8cc"; BORDER_INACTIVE="1E3848aa"
    SURFACE="#101C26"; SURFACE_LOW="#101C26"; SURFACE_CONTAINER="#162838"
    SURFACE_CONTAINER_HIGH="#1E3848"; SURFACE_BRIGHT="#2A4A60"
    TEXT_SECONDARY="#7A9AA8"; TOGGLE_OFF="#2A4A60"
    PRIMARY_CONTAINER="#103858"; ON_PRIMARY_CONTAINER="#C0E4F5"
    ERROR_CONTAINER="#4A2830"; ON_ERROR_CONTAINER="#F5D8DE"
    ;;
  *)
    echo "Unknown theme: $THEME" >&2
    exit 1
    ;;
esac

mkdir -p "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0" "$HOME/.config/rofi"

# Helper: convert #RRGGBB to "R, G, B"
hex_to_rgb() {
    local hex="${1#\#}"
    printf "%d, %d, %d" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

# ── A) GTK4 named-color overrides ─────────────────────────────────────────
cat > "$HOME/.config/gtk-4.0/gtk.css" << CSSEOF
/* Generated by apply-theme.sh ($THEME) -- do not edit */
@define-color accent_color ${ACCENT};
@define-color accent_bg_color ${ACCENT};
@define-color accent_fg_color ${BG};
@define-color destructive_bg_color ${ERROR_CONTAINER};
@define-color destructive_fg_color ${ON_ERROR_CONTAINER};
@define-color destructive_color ${CRITICAL};
@define-color success_bg_color #374B3E;
@define-color success_fg_color #D1E9D6;
@define-color success_color #B5CCBA;
@define-color warning_bg_color #4A3A20;
@define-color warning_fg_color #F0E8D0;
@define-color warning_color ${WARNING};

@define-color window_bg_color ${BG};
@define-color window_fg_color ${TEXT};
@define-color headerbar_bg_color ${SURFACE_CONTAINER};
@define-color headerbar_fg_color ${TEXT};
@define-color headerbar_backdrop_color ${SURFACE_LOW};
@define-color headerbar_backdrop_fg_color ${TEXT_SECONDARY};
@define-color card_bg_color ${SURFACE_LOW};
@define-color card_fg_color ${TEXT};
@define-color popover_bg_color ${SURFACE_CONTAINER_HIGH};
@define-color popover_fg_color ${TEXT};
@define-color dialog_bg_color ${SURFACE_CONTAINER};
@define-color dialog_fg_color ${TEXT};
@define-color view_bg_color ${BG};
@define-color view_fg_color ${TEXT};
@define-color sidebar_bg_color ${SURFACE_CONTAINER};
@define-color sidebar_fg_color ${TEXT};
@define-color sidebar_backdrop_color ${SURFACE_LOW};
@define-color sidebar_backdrop_fg_color ${TEXT_SECONDARY};
@define-color secondary_sidebar_bg_color ${SURFACE_LOW};
@define-color secondary_sidebar_fg_color ${TEXT};
@define-color sidebar_row_active_bg_color ${PRIMARY_CONTAINER};
@define-color sidebar_row_active_fg_color ${ON_PRIMARY_CONTAINER};
@define-color thumbnail_bg_color ${SURFACE_BRIGHT};
@define-color thumbnail_fg_color ${TEXT};
@define-color outline ${TOGGLE_OFF};
@define-color outline_strong ${SURFACE_CONTAINER_HIGH};

@define-color surface_container_lowest ${BG};
@define-color surface_container_low ${SURFACE_LOW};
@define-color surface_container ${SURFACE_CONTAINER};
@define-color surface_container_high ${SURFACE_CONTAINER_HIGH};
@define-color surface_container_highest ${SURFACE_BRIGHT};
@define-color on_surface ${TEXT};
@define-color on_surface_variant ${TEXT_SECONDARY};
@define-color surface_variant ${SURFACE_CONTAINER};
@define-color inverse_surface ${TEXT};
@define-color inverse_on_surface ${BG};
@define-color inverse_primary ${ACCENT};

* {
  caret-color: @accent_color;
}

window {
  background: @window_bg_color;
}

.text-button,
button,
popover.background > contents,
.navigation-sidebar row,
switch slider {
  border-radius: 999px;
}
CSSEOF

# ── B) GTK3 palette ───────────────────────────────────────────────────────
cat > "$HOME/.config/gtk-3.0/gtk.css" << CSSEOF
/* Generated by apply-theme.sh ($THEME) -- do not edit */
@define-color bg_color ${BG};
@define-color fg_color ${TEXT};
@define-color base_color ${BG};
@define-color text_color ${TEXT};
@define-color selected_bg_color ${ACCENT};
@define-color selected_fg_color ${BG};
@define-color tooltip_bg_color ${SURFACE_CONTAINER_HIGH};
@define-color tooltip_fg_color ${TEXT};
@define-color theme_bg_color ${BG};
@define-color theme_fg_color ${TEXT};
@define-color theme_base_color ${BG};
@define-color theme_text_color ${TEXT};
@define-color theme_selected_bg_color ${ACCENT};
@define-color theme_selected_fg_color ${BG};
@define-color theme_unfocused_bg_color ${SURFACE_LOW};
@define-color theme_unfocused_fg_color ${TEXT_SECONDARY};
@define-color theme_unfocused_base_color ${BG};
@define-color theme_unfocused_text_color ${TEXT_SECONDARY};
@define-color borders ${SURFACE_CONTAINER};
@define-color unfocused_borders ${SURFACE_LOW};
@define-color warning_color ${WARNING};
@define-color error_color ${CRITICAL};
@define-color success_color ${CHARGING};
@define-color insensitive_bg_color ${SURFACE_LOW};
@define-color insensitive_fg_color ${TEXT_SECONDARY};
CSSEOF

# ── C) Hyprland border colors ────────────────────────────────────────────
hyprctl keyword general:col.active_border "rgba(${BORDER_ACTIVE})" 2>/dev/null || true
hyprctl keyword general:col.inactive_border "rgba(${BORDER_INACTIVE})" 2>/dev/null || true

# ── D) Rofi launcher colors (colors.rasi is what launcher.rasi imports) ──
cat > "$HOME/.config/rofi/colors.rasi" << ROFIEOF
* {
    bg-panel:         rgba($(hex_to_rgb "$BG"), 80%);
    bg-container:     rgba($(hex_to_rgb "$SURFACE_CONTAINER"), 80%);
    bg-container-hi:  ${SURFACE_CONTAINER_HIGH};
    bg-bright:        ${SURFACE_BRIGHT};
    accent:           ${ACCENT};
    accent-dim:       rgba($(hex_to_rgb "$ACCENT"), 18%);
    text-primary:     ${TEXT};
    text-secondary:   ${TEXT_SECONDARY};
    separator-line:   rgba($(hex_to_rgb "$TEXT"), 10%);
}
ROFIEOF